Add plenty of new magic and very useful stuff

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -1,3 +1,4 @@
+# shellcheck disable=SC2148
 # -*- shell-script -*-
 # vim:set ft=sh textwidth=0 wrapmargin=0:
 set +x
@@ -96,6 +97,7 @@ alias xcode="open *.xcodeproj"
 
 function tarfolder() { tar -czf "$1".tar.gz "$1"/*; }
 function zipfolder() { zip --recurse-paths "$1".zip "$1"/*; }
+function zipfolder_with_password() { zip --encrypt --recurse-paths "$1".zip "$1"/*; }
 
 # SSH
 alias sendstud='~/scripts/sendstud.sh'
@@ -120,14 +122,17 @@ alias gitm='git merge'
 alias gitb='git branch'
 alias gitk='gitk --all'
 alias gitundocommit='git reset --soft HEAD~1'
+
 alias grb='git rebase master'
+alias grm='git rebase master'
+alias grd='git rebase develop'
+
 alias gri='git rebase integration'
 alias gd='git diff'
 alias gcw='git commit -m "WIP $(date)"'
 alias gcm='git checkout master'
 alias gg='git add -A && gcw && git squash 2'
 alias gp='git pull'
-alias grm='git rebase master'
 alias gra='git rebase --abort'
 alias grc='git rebase --continue'
 alias grs='git rebase --skip'
@@ -135,6 +140,7 @@ alias gsa='git stash apply'
 alias gpom='git push origin master'
 alias gca='git commit --amend'
 alias gacw='git add . && gcw'
+alias gcb='git checkout -b'
 
 # Set `indent` parameters according to Linux kernel Coding Style
 #alias indent='indent -kr -i8'
@@ -158,7 +164,7 @@ alias ......="cd ../../.."
 # function hh() { cd $(cat /tmp/last_path); }
 
 alias webserver='python3 -m http.server 8080'
-alias gprer='grep -R'
+alias gprer='grep --recursive'
 
 alias hgrep='history | grep -i'
 
@@ -381,7 +387,8 @@ function up() {
 }
 
 # JSON pretty print
-alias jsonpp='python -m json.tool'
+alias json_pretty_print='python -m json.tool'
+alias jsonpp=json_pretty_print
 
 # Git
 function gc() {
@@ -676,6 +683,9 @@ function update_packages_mac() {
     # Fix casks with `depends_on` that reference pre-Mavericks
     /usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/sed -i '' '/depends_on macos:/d'
 
+    # Somtimes needed to run before 'brew update'
+    git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
+    git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow
     brew update
     brew upgrade
     brew upgrade --cask --force
@@ -715,18 +725,21 @@ function update_xcode() {
     xcode-select --install
 }
 
+function update_pip_packages() {
+      pip list --outdated --format=freeze | \grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
+  }
+
 function update_all() {
     sudo_keep_alive
 
     pushd ~ &> /dev/null # to correctly update global NPM packages
 
-    update_xcode
+    # This sometimes breaks Homebrew taps upgrade
+    # update_xcode
 
-    omz update
-    update_packages_mac;
+    omz update --unattended
     echo "Updating Vim plugins..."
     vim -i NONE -c VundleUpdate -c quitall &> /dev/null
-    echo "Updating npm packages..."
 
     # echo "Updating macOS (if updates available)"
     # softwareupdate -i -a
@@ -736,15 +749,22 @@ function update_all() {
     # Do the rest without sudo
     sudo --reset-timestamp
 
-    npm update -g;
-    npm i npm;
+    # echo "Updating npm packages..."
+    # npm update -g;
+    # npm i npm;
     echo "Updating PIP packages..."
-    pip3 install --upgrade pip;
+    # pip3 install --upgrade pip --user;
+    # Running it twice seems to resolve some dependency issues which PIP reports when running it just one time
+    update_pip_packages; update_pip_packages
     mas upgrade;
+
+    echo "Updating Homebrew packages"
+    update_packages_mac;
 
     popd &> /dev/null 
 
     printf "Updated all applications on %s\n" "`date`" >> ~/update_log.txt 
+    rm -f ~/package.json
 }
 
 function merge_and_push_branch() {
@@ -821,21 +841,21 @@ function filename_extension() {
 # Converts SVG to PNG
 # Usage svg_to_png input_image_path [output_image_height]
 function svg_to_png() {
-    local filename=`filename_without_extension $1`
+    local filename=`filename_without_extension "$1"`
     local output_filename=$filename.png
     local output_image_height=${2:-32}
-    rsvg-convert -h $output_image_height $1 > "$output_filename" && echo "Successfully created $output_filename" || echo "Error converting $1 to $output_filename"
+    rsvg-convert -h "$output_image_height" "$1" > "$output_filename" && echo "Successfully created $output_filename" || echo "Error converting $1 to $output_filename"
 }
 
 function webptopng() {
-    local filename=`filename_without_extension $1`
+    local filename=$(filename_without_extension "$1")
     local output_filename=$filename.png
     local output_image_height=${2:-32}
-    dwebp $1 -o $output_filename
+    dwebp "$1" -o "$output_filename"
 }
 
 function pdftojpg() {
-    pdfimages -j $1 page
+    pdfimages -j "$1" page
 }
 
 function android_update() {
@@ -843,7 +863,7 @@ function android_update() {
 }
 
 function last_modified_directory() {
-    echo `\ls -t | head -n 1`
+    echo $(\ls -t | head -n 1)
 }
 
 function convert_all_files() {
@@ -877,21 +897,21 @@ alias mac_serial_number="system_profiler SPHardwareDataType | \grep '      Seria
 function save_chrome_extension_list() {
     local OUTPUT_FILE=~/scripts/chrome_extensions.txt
     rm $OUTPUT_FILE;
-    EXT_DIR="/Users/`whoami`/Library/Application Support/Google/Chrome/Default/Extensions";
-    pushd $EXT_DIR
-    for f in `\ls */*/manifest.json`;do cat $f | jq -r '.name' >> $OUTPUT_FILE;done
-    popd
+    EXT_DIR="/Users/$(whoami)/Library/Application Support/Google/Chrome/Default/Extensions";
+    pushd "$EXT_DIR" || exit
+    for f in $(\ls */*/manifest.json);do cat "$f" | jq -r '.name' >> $OUTPUT_FILE;done
+    popd || exit
     cat $OUTPUT_FILE
 }
 
 # Updates scripts repo with current date in the message
 # of the (possibly empty) commit
 function update_scripts_repo() {
-    pushd ~/scripts
+    pushd ~/scripts || exit
     git add .
     git commit --allow-empty --message "Update "$(date +%d-%m-%Y)
     git push origin
-    popd
+    popd || exit
 }
 
 alias nrs='npm run start';
@@ -902,7 +922,7 @@ alias yc='yarn run clean'
 alias yrc='yarn run clean'
 
 function mcd() {
-    mkdir $1 && cd $1
+    mkdir "$1" && cd "$1" || exit
 }
 
 alias npmu='npm install -g npm'
@@ -922,8 +942,8 @@ alias nvm_default='nvm alias default node'
 alias nvm_current='nvm install node --reinstall-packages-from=$(nvm current)'
 
 function mov2mp4() {
-    local filename=`filename_without_extension $1`
-    ffmpeg -i $filename.mov -vcodec h264 -acodec mp2 $filename.mp4
+    local filename=$(filename_without_extension "$1")
+    ffmpeg -i "$filename".mov -vcodec h264 -acodec mp2 "$filename".mp4
 }
 
 # Rename  part of filename in each file in a directory
@@ -942,6 +962,24 @@ function remove_filename_part() {
     done
 }
 
+function add_prefix_to_filename() {
+    local prefix=$1
+    for filename in *; do 
+        [ -f "$filename" ] || continue
+        mv "$filename" "$prefix$filename"
+    done
+}
+
+function add_suffix_to_filename() {
+    local suffix=$1
+    for filename in *; do 
+        [ -f "$filename" ] || continue
+        name=$(filename_without_extension "$filename")
+        extension=$(filename_extension "$filename")
+        mv "$filename" "$name$suffix.$extension"
+    done
+}
+
 # Prints the lsof entry of the process that listens on a given port
 # Usage:
 #   listening firefox
@@ -950,7 +988,7 @@ function listening() {
     if [ $# -eq 0 ]; then
         sudo lsof -iTCP -sTCP:LISTEN -n -P
     elif [ $# -eq 1 ]; then
-        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color $1
+        sudo lsof -iTCP -sTCP:LISTEN -n -P | grep -i --color "$1"
     else
         echo "Usage: listening [pattern]"
     fi
@@ -958,7 +996,7 @@ function listening() {
 
 function get_cookies() {
     local url=$1
-    cgurl  --silent --output /dev/null  --cookie-jar - $url
+    cgurl  --silent --output /dev/null  --cookie-jar - "$url"
 }
 
 alias instagram_dl='instalooter user'
@@ -989,7 +1027,7 @@ function sync_branch_with_master() {
 function resize_to_icon() {
     local input_file=$1
     local output_file=$2
-    convert $input_file -thumbnail '1024x1024>' -gravity center -background transparent -extent 1024x1024 $output_file;
+    convert "$input_file" -thumbnail '1024x1024>' -gravity center -background transparent -extent 1024x1024 "$output_file";
 }
 
 function reinstall_cocoapods() {
@@ -1005,3 +1043,175 @@ function force_remove_brew_cask() {
 alias killfsck='sudo pkill -f fsck'
 
 alias prettify="yarn prettier:fix && gc \"chore: Run Prettier on the entire project\""
+
+function copy_as_base64() {
+    local file_path=$1
+    openssl base64 < "$file_path" | tr -d '\n' | pbcopy
+}
+
+function display_notification() {
+    local title=$1
+    local message=$2
+    osascript -e "display notification \"$message\" with title \"$title\""
+
+    # Growl alternative
+    # growlnotify -n "$title" -m "$message"
+}
+
+# macOS 
+alias reset_wifi='sudo networksetup -setnetworkserviceenabled Wi-Fi off && sleep 2 && sudo networksetup -setnetworkserviceenabled Wi-Fi on'
+
+function save_last_n_lines_to_file() {
+    local LINES=$1
+    local filename=~/tmp/$(date)last_$LINES.txt
+    fc -ln -"$LINES" | head -n "$LINES" > "$filename"
+    fc -ln -"$LINES" | head -n "$LINES" > pbcopy
+    echo "Saved to $filename"
+}
+
+function get_repo_name() {
+    basename -s .git $(git config --get remote.origin.url)
+}
+
+alias mk_iphone_dir='mkdir $(date +%Y%m%d)_iphone_photos'
+
+# Example: apply_to_all_files 'resize_image 50%'
+function apply_to_all_files() {
+    local command=$@
+    for filename in *;
+    do
+        eval "${command} ${filename}";
+    done
+}
+
+# Resizes image in-place
+function resize_image() {
+    local resize_arg=$1
+    local input=$2
+    mogrify -resize "$resize_arg" "$input"
+}
+
+function shellcheck_autofix() {
+    local filename=$1
+    shellcheck --format diff "$filename" | git apply
+}
+
+alias copy_last_command="fc -ln -1 | awk '{\$1=\$1}1' | pbcopy"
+
+# Usage: add_diagonal_watermak filename quoted_watermark_text
+function add_diagonal_watermak() {
+    local filename=$1;
+    local watermark_text=$2;
+
+    convert $filename \
+        \( -size 1500x -background none -fill blue -gravity center \
+        label:"$watermark_text" -trim -rotate -30 \
+        -bordercolor none -border 10 \
+        -write mpr:wm +delete \
+        +clone -fill mpr:wm  -draw 'color 0,0 reset' \) \
+        -compose over -composite \
+        $filename
+    }
+
+# Usage:
+# random_password [password_length] 
+function random_password() {
+    local password_length=${1:-16}
+    # local PWGEN_REMOVE_CHARACTERS=\'\"\@\?\^\&\*\(\)\`\:\~\?\;\:\[\]\{\}\.\,\\\/\|
+    local PWGEN_REMOVE_CHARACTERS=\&\\
+    pwgen --secure --symbols $password_length 1 --remove-chars $PWGEN_REMOVE_CHARACTERS
+}
+
+# Usage:
+# bcrypt_hash password
+function bcrypt_hash() {
+    local password=$1
+    local bcrypt_cost=10
+    htpasswd -bnBC $bcrypt_has "" $password | tr -d ':\n' | sed 's/$2y/$2a/'
+}
+
+function ios_simulator_screenshot() {
+    xcrun simctl io booted screenshot
+}
+
+function ios_simulator_screencast() {
+    xcrun simctl io booted recordVideo ios_simluator_recording.mp4
+}
+
+# returns commit date, author name and commit subject for a date range given
+# Example: commits_between_dates 2020-12-01 2020-12-31
+function commits_between_dates {
+    local date_from=$1
+    local date_to=$2
+    git log --date=iso --pretty=format:'%ad	%aN	%s' | awk '$0 >= "'$date_from'" && $0 <= "'$date_to'"'
+}
+
+function git_delete_tag() {
+    local tagname=$1
+    git tag --delete $tagname
+    git push --delete origin $tagname
+}
+
+alias github_merge_pr='gh pr merge $(git branch --show-current) --delete-branch  --rebase'
+
+# Generate a random 32 character alphanumeric string (upper 
+# and lowercase) and numbers in Bash
+# Alternative
+# tr -dc '[:alnum:]' < /dev/urandom | dd bs=4 count=8 2>/dev/null
+function random-string() {
+# Add special chars:
+# env LC_ALL=C tr -dc '(\&\_a-zA-Z0-9\^\*\@'
+cat /dev/urandom | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
+}
+
+function brew_cleanup_package() {
+    local package_name=$1
+
+    # don't use reinstall
+    brew uninstall -f $package_name
+
+    # remove possible broken symlinks
+    brew cleanup
+
+    # install httping again
+    brew install $package_name
+
+    # check the version
+    brew info $package_name
+}
+
+function reinstall_pip() {
+    python -m pip install --upgrade --force-reinstall pip
+    python3 -m pip install --upgrade --force-reinstall pip
+}
+
+
+# TODO: Move outside of aliases
+alias sync_transmission_settings='cp $HOME/Library/Preferences/org.m0k.transmission.plist ~/dotfiles/'
+
+function convert_to_grayscale() {
+    local input_filename="$1";
+    local filename=`filename_without_extension "$1"`;
+    local output_filename="$filename"_grayscale.png;
+    convert $input_filename -grayscale Rec709Luminance $output_filename;
+}
+
+alias gl='git log'
+alias copy_branch_name_to_clipboard='git branch --show-current | pbcopy'
+# macOS only
+alias analyze_disk_usage='/Applications/OmniDiskSweeper.app/Contents/MacOS/OmniDiskSweeper'
+
+function webm_to_mp4 () {
+    local filename=`filename_without_extension "$1"`
+    local output_filename=$filename.mp4
+    local output_image_height=${2:-32}
+    local fps=24
+    ffmpeg -hide_banner -loglevel error -fflags +genpts -i "$1" -r $fps "$output_filename"  && echo "Successfully created $output_filename" || echo "Error converting $1 to $output_filename"
+}
+
+# Toggle "Do not disturb" mode on macOS (via: https://github.com/sindresorhus/do-not-disturb-cli)
+alias dnd-toggle='dnd toggle'
+
+# Copy command output to clipboard
+# Usage: echo 'Hello world' | t
+alias t='tee >(pbcopy)'
